# Generated by Django 5.2.6 on 2025-10-02 16:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_photo_image_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text='Hero image for your profile page',
                max_length=255,
                verbose_name='hero_image'),
        ),
    ]
